### ISSUE TITLE
Question: rely on dependencies provided by spring boot

### ISSUE THREAD

**Issue by eddumelendez** [scotiabank/accelerator-initializer#12]
Currently, `spring-boot` provides dependency management for these dependencies. Shall we rely on these properties? are we using these specific versions for any reason?

https://github.com/scotiabank/accelerator-initializer/blob/abe63933595ac5d6a661e6dffaa2f45e5d88c631/build.gradle#L62-L64

**Comment by christophe-f** [comment]
I would stick with the ones provided by Spring Boot.
