### ISSUE TITLE
Consider renaming package

### ISSUE THREAD

**Issue by eddumelendez** [scotiabank/accelerator-initializer#13]
Project name is `accelerator-initializer` and the package said `com.hopper`. IMHO, package name should be `com.scotiabank.accelerator.initializer` or `com.scotiabank.initializer`. WDYT?

**Comment by yshewchuk** [comment]
We definitely need to rename the packages - scotiabank is very clear, but a bit long. I've seen some other projects that use the bns abbreviation. Not sure if that'll be clear externally, though. What do you think about just "scotia" to shorten it a bit?

As for `accelerator.initializer` or `initializer`, I think probably `accelerator.initializer` makes the most sense. The long term vision is to release a suite of products that work closely together called accelerator, so I can see them all falling under that accelerator package. That also makes the package names quite long, so maybe we shouldn't worry about shortening scotiabank haha.

I guess I agree with `com.scotiabank.accelerator.initializer`

**Comment by christophe-f** [comment]
I'm good for `com.scotiabank.accelerator.initializer` . That will make life easier when many packages will be published on Maven Central/Bintray

**Comment by dkuwahara** [comment]
I would take out "scotiabank". I'm pretty sure that's not allowed

**Comment by madhurkumar** [comment]
"bns" could be precise and generally acceptable

**Comment by alicoding** [comment]
I don't think we should really associate either `bns` or `scotiabank` into this open source project at all.

**Comment by eddumelendez** [comment]
have you considered released projects under `accelerator`? So the package name should be `com.accelerator.initializer` for this project.

TBH, this approach will be weird since the organization is `Scotiabank` and the expected package should contain the organization name but can be an option that can be discussed.

**Comment by alicoding** [comment]
Thinking about it again now I think using Scotiabank there should be fine for naming package only. I guess I was thinking more about other things at the time.
