### ISSUE TITLE
bug(templating): could not Initialise a new project because of a template not found exception

### ISSUE THREAD

**Issue by jantoniucci** [scotiabank/accelerator-initializer#16]
Following the instructions provided to initialise a new project, I got an error related to a template not found exception.

To reproduce it, launch the app using `./gradlew bootRun` 

and then 

`curl -X POST "http://localhost:8086/api/projects/ciadKey/components/download" -H "accept: */*" -H "Content-Type: application/json" -d "{ \"name\": \"boot-app-2\", \"projectKey\": \"hopper\", \"type\": \"JAVA_SPRING_BOOT_2\"}"`

returns:

`{"timestamp":"2018-08-01T21:28:16.987+0000","status":500,"error":"Internal Server Error","exception":"java.lang.IllegalStateException","message":"Cannot render template","path":"/api/projects/ciadKey/components/download`

At the console:

`java.io.FileNotFoundException: class path resource [templates/projectCreation/gitignore.tpl.html] cannot be opened because it does not exist
        at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:172) ~[spring-core-4.3.18.RELEASE.jar:4.3.18.RELEASE]
        at org.springframework.boot.autoconfigure.mustache.MustacheResourceTemplateLoader.getTemplate(MustacheResourceTemplateLoader.java:81) ~[spring-boot-autoconfigure-1.5.15.RELEASE.jar:1.5.15.RELEASE]
        at com.hopper.initializer.MustacheRenderer.loadTemplate(MustacheRenderer.java:74) ~[main/:na]`

**Comment by dkuwahara** [comment]
Looks to be caused by https://github.com/scotiabank/accelerator-initializer/commit/e79e78aef7fb2842995a4a4816fe1d1b67e44d75

@eddumelendez

**Comment by christophe-f** [comment]
The default Mustache suffix is `.html`

You can set the following property to fix this:
spring.mustache.suffix=

Will submit a PR now

**Comment by eddumelendez** [comment]
I can see some improvements here.

* Remove the `.html` suffix in all `*ClassCreator` E.g https://github.com/scotiabank/accelerator-initializer/blob/9338c68e0855300f97d0d9fdf2aad7409f0f0445/src/main/java/com/hopper/initializer/creator/java/SpringBootApplicationTestClassCreator.java#L30
* Add `spring.mustache.suffix` configuration property with the value `.tpl`
* Add tests to ensure templates are loaded properly

**Comment by jantoniucci** [comment]
Thanks a lot! I fixed it in my local clone but there are many many paths / suffix fixed at the code, tests to be updated, etc so I prefer to wait for your official fix.

**Comment by yshewchuk** [comment]
Updating all the suffixes in the code and tests is probably not required right now - I'm in the midst of creating a roadmap which will drastically change how the templates are loaded, so it may no longer be required after that.

**Comment by eddumelendez** [comment]
@yshewchuk should I create a issue with the enhancements I mentioned in the [previous comment](url)https://github.com/scotiabank/accelerator-initializer/issues/16#issuecomment-409936930? Just to track them

**Comment by yshewchuk** [comment]
@eddumelendez by all means - once the roadmap is up we can see if it'll be helpful :)
