### ISSUE TITLE
Race condition with project creation

### ISSUE THREAD

**Issue by yshewchuk** [scotiabank/accelerator-initializer#33]
If two projects with the same project key and name values are requested at approximately the same time the results would interfere with each other and one request may fail outright, or download with only a partial set of files.

**Comment by lucaskenjiii** [comment]
I can see two options here

1) Drop Initiliazer config and move Files.createTempDir().getAbsolutePath() to ComponentController
```
private String initProjectDir(ComponentAddRequest request) {
        String tempPath = Files.createTempDir().getAbsolutePath();
        String projectName = String.format(TEMP_PATH, request.getProjectKey().toLowerCase(), request.getName().toLowerCase());
        File path = Paths.get(tempPath, projectName).toFile();
        fileProcessor.createDirectories(path);
        log.info("Creating path {} ", path);
        return path.getAbsolutePath();
    }
```

2) Just append an uuid to your path
