### ISSUE TITLE
Remove settings.gradle file

### ISSUE THREAD

**Issue by dkuwahara** [scotiabank/accelerator-initializer#41]
I don't think this is actually useful here
https://github.com/scotiabank/accelerator-initializer/blob/8fb49262cb4e1ebe167eb9b90a0ff97d3270df59/settings.gradle#L1

**Comment by yshewchuk** [comment]
It does provide some value (maybe not a lot). If this is not specified, then it will use the directory name as the project name. Which would mean that the jar file that is created could potentially be different for different people, this makes the build more deterministic. But maybe we should update this to match the repo name? @dkuwahara

**Comment by yshewchuk** [comment]
@dkuwahara can we close this off, or do you have some additional concern with this?
