### ISSUE TITLE
Upgrade to spring-boot 2.0.x

### ISSUE THREAD

**Issue by eddumelendez** [scotiabank/accelerator-initializer#5]

**Comment by eddumelendez** [comment]
depends #7

**Comment by christophe-f** [comment]
I think the Lombok version is not longer required to be hardcoded with Spring Boot 2.0

Also some Actuator properties are deprecated in the application.yml. Adding this in the build.gradle will help to identify them:
runtime("org.springframework.boot:spring-boot-properties-migrator")

**Comment by yshewchuk** [comment]
Yes, it looks like you're right - the actuator properties have changed slightly. I will re-open the issue to address this. As for the lombok version, it looks like it doesn't hurt to explicitly state the version, so I'm on the fence about that.

**Comment by eddumelendez** [comment]
I'll be sending another PR with these changes

**Comment by eddumelendez** [comment]
If `lombokVersion` is removed we will have an [issue](https://github.com/spring-projects/spring-boot/issues/13492#issuecomment-397614616). By default, lombok `1.16.22` is provided by spring boot `2.0.4.RELEASE`

**Comment by yshewchuk** [comment]
I took a look at the lombok issue - I think that technically we will not have an issue with that particular change to lombok (apparently it only applies to @Data and @Value annotations), but I share the concern that implicitly updating lombok versions could cause failures. I'd prefer to keep the version specified to keep the builds deterministic.
